### ISSUE TITLE
set LLVM11_HOME but meet error: LLVM11_HOME not set

### ISSUE THREAD

**Issue by Thespica** [alibaba/fastFFI#38]
When I run `mvn clean install`, meet error: LLVM11_HOME not set.
![Screenshot (106)](https://github.com/alibaba/fastFFI/assets/119573640/88b2a8f9-8632-4aa0-86a8-1b16dbff4923)
I tried #5 but it didn't work.
![Screenshot (105)](https://github.com/alibaba/fastFFI/assets/119573640/1e19ddf3-8c43-4f35-a4d4-069c7a5d3a6f)
I also tried compile source code, it also didn't work.
Environment: wsl Ubuntu 20.04

**Comment by sighingnow** [comment]
If you running `mvn clean install` with `sudo`, you need `sudo -E mvn clean install`.

**Comment by Thespica** [comment]
Thanks, it solve this problem. Unfortunately, I met another problem:


![Screenshot (108)](https://github.com/alibaba/fastFFI/assets/119573640/0e94871c-e5bc-47c7-805f-f9e0ba6c21b2)

![Screenshot (109)](https://github.com/alibaba/fastFFI/assets/119573640/ec7e39ff-cef3-4672-ba46-f5484a558017)

Here is my environment:

wsl ubuntu 20.04.

llvm-11, installed by running `sudo ./llvm.sh 11`.

`cmake version 3.16.3`

`Apache Maven 3.6.3`  This time I ran `mvn clean install` rather than `sudo mvn clean install` or `sudo -E mvn clean install`.

`openjdk version "1.8.0_362"`.

Thanks again.

**Comment by sighingnow** [comment]
Have no idea about the error without full error logs. Instead of setup dependencies in your machine, you could try with the docker image that tested by our CI: https://github.com/alibaba/fastFFI/blob/main/.github/workflows/linux.yml#L33

**Comment by Thespica** [comment]
Thanks a lot <3.

**Comment by Thespica** [comment]
I installed llvm11 on Ubuntu-20.04 successfuly by using [the script](https://github.com/alibaba/fastFFI/blob/main/docker/install-llvm11.sh) with `LLVM11_HOME=/usr/lib/llvm-11` and `LLVM_VAR=11.0.0`.

BTW, I think installing llvm by the way which #5 recommended might leads error below:
```
[ERROR] : CommandLine Error: Option 'help-list' registered more than once!
[ERROR] LLVM ERROR: inconsistency in registered CommandLine options
[ERROR] Aborted
```
