### ISSUE TITLE
请问需要自己编译llvm么，还是使用直接使用二进制安装也可以呢

### ISSUE THREAD

**Issue by elroy93** [alibaba/fastFFI#5]
在mvn install的过程中遇到了一些问题。 我使用的是llvm下载的ubuntu的二进制包。
请问需要自己编译llvm么，还是使用直接使用二进制安装也可以呢
-- 
环境 wsl & ubuntu20

![image](https://user-images.githubusercontent.com/43977905/143981576-e740659f-0244-44e4-a12a-9f96a6c5833e.png)

![image](https://user-images.githubusercontent.com/43977905/143981559-90f20bba-32e8-4acb-b761-c86fcd9eeb39.png)

**Comment by tianxiaogu** [comment]
这个可能是安装的方式不完整，缺少lld，建议按照 <https://apt.llvm.org/> 来安装LLVM，然后默认的安装目录应该是`/usr/lib/llvm-11`.

```
For convenience there is an automatic installation script available that installs LLVM for you.
To install the latest stable version:
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

To install a specific version of LLVM:
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh <version number> # 这里使用版本号11
```

**Comment by elroy93** [comment]
thanks ~
