### ISSUE TITLE
Building fails: no member named 'getUsingDecl' in 'clang::ConstructorUsingShadowDecl'

### ISSUE THREAD

**Issue by HGuillemet** [alibaba/fastFFI#8]
Hi,

This project seems  promising and I wanted to give it a try but I get the following error when building, either with llvm 11 or 13:

```
[INFO]      [exec] /usr/lib/llvm/11/bin/clang++ -Dllvm4jni_EXPORTS -I/usr/lib/llvm/13/include -isystem /opt/openjdk/include -isystem /opt/openjdk/include/linux -flto -fforce-emit-vtables -std=c++14 -Wall -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -MD -MT CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o -MF CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o.d -o CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o -c /home/java/fastFFI/llvm/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc
[INFO]      [exec] /home/java/fastFFI/llvm/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_ConstructorUsingShadowDecl_cxx_0xefa0f2e5.cc:98:92: error: no member named 'getUsingDecl' in 'clang::ConstructorUsingShadowDecl'
[INFO]      [exec]         return reinterpret_cast<jlong>(reinterpret_cast<clang::ConstructorUsingShadowDecl*>(ptr)->getUsingDecl());
[INFO]      [exec]                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
```

Any idea ?

**Comment by tianxiaogu** [comment]
@HGuillemet 

Thank you very much for your interest in fastFFI!

fastFFI was built on top of C++ API of Clang and LLVM and these C++ APIs are not stable. A C++ API may be only available in some minor versions. We have tested fastFFI on Mac OS with LLVM 11.1.0_3 (installed via home brew).

We also included many unused API to Java via fastFFI during the development. Here is an example. To solve your specific problem, you can simply remove method `getUsingDecl` in `UsingShadowDecl.java`. We will remove these unused LLVM/Clang APIs in the future when fastFFI is stable.

**Comment by sighingnow** [comment]
> Hi,
> 
> This project seems promising and I wanted to give it a try but I get the following error when building, either with llvm 11 or 13:
> 
> ```
> [INFO]      [exec] /usr/lib/llvm/11/bin/clang++ -Dllvm4jni_EXPORTS -I/usr/lib/llvm/13/include -isystem /opt/openjdk/include -isystem /opt/openjdk/include/linux -flto -fforce-emit-vtables -std=c++14 -Wall -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -MD -MT CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o -MF CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o.d -o CMakeFiles/llvm4jni.dir/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc.o -c /home/java/fastFFI/llvm/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_DeclaratorDecl_cxx_0x7852b4ac.cc
> [INFO]      [exec] /home/java/fastFFI/llvm/target/generated-sources/annotations/jni_com_alibaba_fastffi_clang_ConstructorUsingShadowDecl_cxx_0xefa0f2e5.cc:98:92: error: no member named 'getUsingDecl' in 'clang::ConstructorUsingShadowDecl'
> [INFO]      [exec]         return reinterpret_cast<jlong>(reinterpret_cast<clang::ConstructorUsingShadowDecl*>(ptr)->getUsingDecl());
> [INFO]      [exec]                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
> ```
> 
> Any idea ?

We now have a CI on github to verify the compatibility with llvm 11, using the the public [teeks99/clang-ubuntu:11](https://hub.docker.com/r/teeks99/clang-ubuntu) docker image.

For detailed reproducible build & test steps, you could refer to https://github.com/alibaba/fastFFI/blob/main/.github/workflows/linux.yml.
